name: skinsafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2
 

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.14.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  supabase_flutter: ^2.8.4
  crop_your_image: ^2.0.0
  string_similarity: ^2.1.1
  provider: ^6.1.4
  google_mlkit_face_detection: ^0.12.0
  path_provider: ^2.1.1
  path: ^1.8.3
  google_mlkit_commons: 0.9.0
  google_ml_kit: ^0.19.0
  image: ^4.5.4
  http: ^1.3.0
  app_links: ^6.4.0
  tflite_flutter: 0.10.4
  collection: ^1.19.1
  crop_image: ^1.0.10  # Check pub.dev for the latest stable version
  intl: ^0.20.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/skinsafeLogo.png
    - assets/SafetyScale.png
    - assets/placeholder.png
    - assets/skincare.png
    - assets/skincare2.jpeg
    - assets/google_logo.png
    - assets/skincare_routine_builder_logo.png
    - assets/check_product_safety_rating_logo.png
    - assets/skincare_product_suitability_logo.png
    - assets/avatar.png
    - assets/skin compass.png

    - assets/models/skin_type_model16.tflite # Assuming you place models here ( 4 classes)
    - assets/models/skin_type_model32.tflite # Assuming you place models here ( 4 classes)
    - assets/labels/skin_type_labels(4_classes).txt # Assuming you place labels here ( 4 classes)

    - assets/models/3_class_best_float16.tflite # New skin type detection model ( 3 classes)
    - assets/models/3_class_best_float32.tflite # New skin type detection model ( 3 classes)
    - assets/labels/skin_type_labels(3_classes).txt # Assuming you place labels here ( 3 classes)

    #Resnet model with accurcy 86%
    - assets/models/resnet50_best.tflite
    - assets/skin_compass/decadeGuides.json
