name: skinsafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.14.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  supabase_flutter: ^2.8.4
  crop_your_image: ^2.0.0
  string_similarity: ^2.1.1
  provider: ^6.1.4
  google_mlkit_face_detection: ^0.12.0
  path_provider: ^2.1.1
  path: ^1.8.3
  google_mlkit_commons: 0.9.0
  google_ml_kit: ^0.19.0
  image: ^4.5.4
  http: ^1.3.0
  app_links: ^6.4.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/skinsafeLogo.png
    - assets/SafetyScale.png
    - assets/placeholder.png
    - assets/skincare.png
    - assets/skincare2.jpeg
    - assets/google_logo.png
